/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'estimatedPrice' : number,
  'productId' : [] | [ProductId],
  'quantity' : bigint,
  'customItemName' : [] | [string],
}
export interface ChatMessage {
  'id' : MessageId,
  'orderId' : OrderId,
  'message' : string,
  'timestamp' : Time,
  'senderRole' : SenderRole,
  'senderId' : Principal,
}
export type MessageId = number;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'shopId' : ShopId,
  'deliveryFee' : number,
  'createdAt' : Time,
  'finalTotal' : [] | [number],
  'updatedAt' : Time,
  'estimatedTotal' : number,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
  'adminNotes' : string,
}
export type OrderId = number;
export interface OrderItem {
  'status' : OrderItemStatus,
  'confirmedPrice' : [] | [number],
  'estimatedPrice' : number,
  'alternativeSuggestion' : string,
  'itemName' : string,
  'quantity' : bigint,
}
export type OrderItemIndex = number;
export type OrderItemStatus = { 'substituted' : null } |
  { 'pending' : null } |
  { 'confirmed' : null } |
  { 'unavailable' : null };
export type OrderStatus = { 'outForDelivery' : null } |
  { 'rejected' : null } |
  { 'delivered' : null } |
  { 'shoppingInProgress' : null } |
  { 'received' : null } |
  { 'checkingAvailability' : null };
export interface Product {
  'id' : ProductId,
  'shopId' : ShopId,
  'estimatedPrice' : number,
  'name' : string,
  'isAvailable' : boolean,
  'category' : string,
}
export type ProductId = number;
export type SenderRole = { 'admin' : null } |
  { 'customer' : null };
export interface Shop {
  'id' : ShopId,
  'closeTime' : string,
  'name' : string,
  'isOpen' : boolean,
  'distanceKm' : number,
  'address' : string,
  'phone' : string,
  'openTime' : string,
}
export type ShopId = number;
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[ShopId, string, string, number], ProductId>,
  'addShop' : ActorMethod<
    [string, number, string, string, string, string],
    ShopId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmOrder' : ActorMethod<[OrderId, number], undefined>,
  'confirmOrderItem' : ActorMethod<
    [OrderId, OrderItemIndex, number],
    undefined
  >,
  'createOrder' : ActorMethod<[ShopId, Array<CartItem>], OrderId>,
  'editOrderItemPrice' : ActorMethod<
    [OrderId, OrderItemIndex, number],
    undefined
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrderById' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrderChat' : ActorMethod<[OrderId], Array<ChatMessage>>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProductsByShop' : ActorMethod<[ShopId], Array<Product>>,
  'getProductsByShopSortedByPrice' : ActorMethod<[ShopId], Array<Product>>,
  'getShopById' : ActorMethod<[ShopId], [] | [Shop]>,
  'getShops' : ActorMethod<[], Array<Shop>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectOrder' : ActorMethod<[OrderId, string], undefined>,
  'rejectOrderItem' : ActorMethod<[OrderId, OrderItemIndex, string], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'sendAdminChatMessage' : ActorMethod<[OrderId, string], undefined>,
  'sendChatMessage' : ActorMethod<[OrderId, string], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateShopStatus' : ActorMethod<[ShopId, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];