/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ShopId = IDL.Nat32;
export const ProductId = IDL.Nat32;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Nat32;
export const OrderItemIndex = IDL.Nat32;
export const CartItem = IDL.Record({
  'estimatedPrice' : IDL.Float64,
  'productId' : IDL.Opt(ProductId),
  'quantity' : IDL.Nat,
  'customItemName' : IDL.Opt(IDL.Text),
});
export const OrderStatus = IDL.Variant({
  'outForDelivery' : IDL.Null,
  'rejected' : IDL.Null,
  'delivered' : IDL.Null,
  'shoppingInProgress' : IDL.Null,
  'received' : IDL.Null,
  'checkingAvailability' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItemStatus = IDL.Variant({
  'substituted' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
  'unavailable' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'status' : OrderItemStatus,
  'confirmedPrice' : IDL.Opt(IDL.Float64),
  'estimatedPrice' : IDL.Float64,
  'alternativeSuggestion' : IDL.Text,
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'shopId' : ShopId,
  'deliveryFee' : IDL.Float64,
  'createdAt' : Time,
  'finalTotal' : IDL.Opt(IDL.Float64),
  'updatedAt' : Time,
  'estimatedTotal' : IDL.Float64,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
  'adminNotes' : IDL.Text,
});
export const MessageId = IDL.Nat32;
export const SenderRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'orderId' : OrderId,
  'message' : IDL.Text,
  'timestamp' : Time,
  'senderRole' : SenderRole,
  'senderId' : IDL.Principal,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'shopId' : ShopId,
  'estimatedPrice' : IDL.Float64,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'category' : IDL.Text,
});
export const Shop = IDL.Record({
  'id' : ShopId,
  'closeTime' : IDL.Text,
  'name' : IDL.Text,
  'isOpen' : IDL.Bool,
  'distanceKm' : IDL.Float64,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'openTime' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [ShopId, IDL.Text, IDL.Text, IDL.Float64],
      [ProductId],
      [],
    ),
  'addShop' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ShopId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmOrder' : IDL.Func([OrderId, IDL.Float64], [], []),
  'confirmOrderItem' : IDL.Func([OrderId, OrderItemIndex, IDL.Float64], [], []),
  'createOrder' : IDL.Func([ShopId, IDL.Vec(CartItem)], [OrderId], []),
  'editOrderItemPrice' : IDL.Func(
      [OrderId, OrderItemIndex, IDL.Float64],
      [],
      [],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrderChat' : IDL.Func([OrderId], [IDL.Vec(ChatMessage)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByShop' : IDL.Func([ShopId], [IDL.Vec(Product)], ['query']),
  'getProductsByShopSortedByPrice' : IDL.Func(
      [ShopId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getShopById' : IDL.Func([ShopId], [IDL.Opt(Shop)], ['query']),
  'getShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectOrder' : IDL.Func([OrderId, IDL.Text], [], []),
  'rejectOrderItem' : IDL.Func([OrderId, OrderItemIndex, IDL.Text], [], []),
  'seedData' : IDL.Func([], [], []),
  'sendAdminChatMessage' : IDL.Func([OrderId, IDL.Text], [], []),
  'sendChatMessage' : IDL.Func([OrderId, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateShopStatus' : IDL.Func([ShopId, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ShopId = IDL.Nat32;
  const ProductId = IDL.Nat32;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Nat32;
  const OrderItemIndex = IDL.Nat32;
  const CartItem = IDL.Record({
    'estimatedPrice' : IDL.Float64,
    'productId' : IDL.Opt(ProductId),
    'quantity' : IDL.Nat,
    'customItemName' : IDL.Opt(IDL.Text),
  });
  const OrderStatus = IDL.Variant({
    'outForDelivery' : IDL.Null,
    'rejected' : IDL.Null,
    'delivered' : IDL.Null,
    'shoppingInProgress' : IDL.Null,
    'received' : IDL.Null,
    'checkingAvailability' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItemStatus = IDL.Variant({
    'substituted' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
    'unavailable' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'status' : OrderItemStatus,
    'confirmedPrice' : IDL.Opt(IDL.Float64),
    'estimatedPrice' : IDL.Float64,
    'alternativeSuggestion' : IDL.Text,
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'shopId' : ShopId,
    'deliveryFee' : IDL.Float64,
    'createdAt' : Time,
    'finalTotal' : IDL.Opt(IDL.Float64),
    'updatedAt' : Time,
    'estimatedTotal' : IDL.Float64,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
    'adminNotes' : IDL.Text,
  });
  const MessageId = IDL.Nat32;
  const SenderRole = IDL.Variant({ 'admin' : IDL.Null, 'customer' : IDL.Null });
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'orderId' : OrderId,
    'message' : IDL.Text,
    'timestamp' : Time,
    'senderRole' : SenderRole,
    'senderId' : IDL.Principal,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'shopId' : ShopId,
    'estimatedPrice' : IDL.Float64,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'category' : IDL.Text,
  });
  const Shop = IDL.Record({
    'id' : ShopId,
    'closeTime' : IDL.Text,
    'name' : IDL.Text,
    'isOpen' : IDL.Bool,
    'distanceKm' : IDL.Float64,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'openTime' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [ShopId, IDL.Text, IDL.Text, IDL.Float64],
        [ProductId],
        [],
      ),
    'addShop' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ShopId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmOrder' : IDL.Func([OrderId, IDL.Float64], [], []),
    'confirmOrderItem' : IDL.Func(
        [OrderId, OrderItemIndex, IDL.Float64],
        [],
        [],
      ),
    'createOrder' : IDL.Func([ShopId, IDL.Vec(CartItem)], [OrderId], []),
    'editOrderItemPrice' : IDL.Func(
        [OrderId, OrderItemIndex, IDL.Float64],
        [],
        [],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrderChat' : IDL.Func([OrderId], [IDL.Vec(ChatMessage)], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByShop' : IDL.Func([ShopId], [IDL.Vec(Product)], ['query']),
    'getProductsByShopSortedByPrice' : IDL.Func(
        [ShopId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getShopById' : IDL.Func([ShopId], [IDL.Opt(Shop)], ['query']),
    'getShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectOrder' : IDL.Func([OrderId, IDL.Text], [], []),
    'rejectOrderItem' : IDL.Func([OrderId, OrderItemIndex, IDL.Text], [], []),
    'seedData' : IDL.Func([], [], []),
    'sendAdminChatMessage' : IDL.Func([OrderId, IDL.Text], [], []),
    'sendChatMessage' : IDL.Func([OrderId, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateShopStatus' : IDL.Func([ShopId, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };