/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ShopId = number;
export type OrderItemIndex = number;
export type Time = bigint;
export interface OrderItem {
    status: OrderItemStatus;
    confirmedPrice?: number;
    estimatedPrice: number;
    alternativeSuggestion: string;
    itemName: string;
    quantity: bigint;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    shopId: ShopId;
    deliveryFee: number;
    createdAt: Time;
    finalTotal?: number;
    updatedAt: Time;
    estimatedTotal: number;
    customerId: Principal;
    items: Array<OrderItem>;
    adminNotes: string;
}
export type MessageId = number;
export interface ChatMessage {
    id: MessageId;
    orderId: OrderId;
    message: string;
    timestamp: Time;
    senderRole: SenderRole;
    senderId: Principal;
}
export type ProductId = number;
export interface CartItem {
    estimatedPrice: number;
    productId?: ProductId;
    quantity: bigint;
    customItemName?: string;
}
export interface Shop {
    id: ShopId;
    closeTime: string;
    name: string;
    isOpen: boolean;
    distanceKm: number;
    address: string;
    phone: string;
    openTime: string;
}
export type OrderId = number;
export interface Product {
    id: ProductId;
    shopId: ShopId;
    estimatedPrice: number;
    name: string;
    isAvailable: boolean;
    category: string;
}
export enum OrderItemStatus {
    substituted = "substituted",
    pending = "pending",
    confirmed = "confirmed",
    unavailable = "unavailable"
}
export enum OrderStatus {
    outForDelivery = "outForDelivery",
    rejected = "rejected",
    delivered = "delivered",
    shoppingInProgress = "shoppingInProgress",
    received = "received",
    checkingAvailability = "checkingAvailability"
}
export enum SenderRole {
    admin = "admin",
    customer = "customer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(shopId: ShopId, name: string, category: string, estimatedPrice: number): Promise<ProductId>;
    addShop(name: string, distanceKm: number, openTime: string, closeTime: string, phone: string, address: string): Promise<ShopId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmOrder(orderId: OrderId, finalTotal: number): Promise<void>;
    confirmOrderItem(orderId: OrderId, itemIndex: OrderItemIndex, confirmedPrice: number): Promise<void>;
    createOrder(shopId: ShopId, items: Array<CartItem>): Promise<OrderId>;
    editOrderItemPrice(orderId: OrderId, itemIndex: OrderItemIndex, newPrice: number): Promise<void>;
    getAllOrders(): Promise<Array<Order>>;
    getCallerUserRole(): Promise<UserRole>;
    getMyOrders(): Promise<Array<Order>>;
    getOrderById(orderId: OrderId): Promise<Order | null>;
    getOrderChat(orderId: OrderId): Promise<Array<ChatMessage>>;
    getProductById(productId: ProductId): Promise<Product | null>;
    getProductsByCategory(category: string): Promise<Array<Product>>;
    getProductsByShop(shopId: ShopId): Promise<Array<Product>>;
    getProductsByShopSortedByPrice(shopId: ShopId): Promise<Array<Product>>;
    getShopById(shopId: ShopId): Promise<Shop | null>;
    getShops(): Promise<Array<Shop>>;
    isCallerAdmin(): Promise<boolean>;
    rejectOrder(orderId: OrderId, reason: string): Promise<void>;
    rejectOrderItem(orderId: OrderId, itemIndex: OrderItemIndex, alternativeSuggestion: string): Promise<void>;
    seedData(): Promise<void>;
    sendAdminChatMessage(orderId: OrderId, message: string): Promise<void>;
    sendChatMessage(orderId: OrderId, message: string): Promise<void>;
    updateOrderStatus(orderId: OrderId, status: OrderStatus): Promise<void>;
    updateShopStatus(shopId: ShopId, isOpen: boolean): Promise<void>;
}
import type { CartItem as _CartItem, ChatMessage as _ChatMessage, MessageId as _MessageId, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderItemStatus as _OrderItemStatus, OrderStatus as _OrderStatus, Product as _Product, ProductId as _ProductId, SenderRole as _SenderRole, Shop as _Shop, ShopId as _ShopId, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: ShopId, arg1: string, arg2: string, arg3: number): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addShop(arg0: string, arg1: number, arg2: string, arg3: string, arg4: string, arg5: string): Promise<ShopId> {
        if (this.processError) {
            try {
                const result = await this.actor.addShop(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShop(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmOrder(arg0: OrderId, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmOrder(arg0, arg1);
            return result;
        }
    }
    async confirmOrderItem(arg0: OrderId, arg1: OrderItemIndex, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmOrderItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmOrderItem(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrder(arg0: ShopId, arg1: Array<CartItem>): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async editOrderItemPrice(arg0: OrderId, arg1: OrderItemIndex, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editOrderItemPrice(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editOrderItemPrice(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderById(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderChat(arg0: OrderId): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderChat(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderChat(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductById(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(arg0);
            return result;
        }
    }
    async getProductsByShop(arg0: ShopId): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByShop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByShop(arg0);
            return result;
        }
    }
    async getProductsByShopSortedByPrice(arg0: ShopId): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByShopSortedByPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByShopSortedByPrice(arg0);
            return result;
        }
    }
    async getShopById(arg0: ShopId): Promise<Shop | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopById(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopById(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShops(): Promise<Array<Shop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShops();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShops();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectOrder(arg0: OrderId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectOrder(arg0, arg1);
            return result;
        }
    }
    async rejectOrderItem(arg0: OrderId, arg1: OrderItemIndex, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectOrderItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectOrderItem(arg0, arg1, arg2);
            return result;
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async sendAdminChatMessage(arg0: OrderId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAdminChatMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAdminChatMessage(arg0, arg1);
            return result;
        }
    }
    async sendChatMessage(arg0: OrderId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0, arg1);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateShopStatus(arg0: ShopId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShopStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShopStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ChatMessage_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_OrderItemStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderItemStatus): OrderItemStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_OrderItem_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderItem): OrderItem {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SenderRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SenderRole): SenderRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Shop]): Shop | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderItemStatus;
    confirmedPrice: [] | [number];
    estimatedPrice: number;
    alternativeSuggestion: string;
    itemName: string;
    quantity: bigint;
}): {
    status: OrderItemStatus;
    confirmedPrice?: number;
    estimatedPrice: number;
    alternativeSuggestion: string;
    itemName: string;
    quantity: bigint;
} {
    return {
        status: from_candid_OrderItemStatus_n15(_uploadFile, _downloadFile, value.status),
        confirmedPrice: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.confirmedPrice)),
        estimatedPrice: value.estimatedPrice,
        alternativeSuggestion: value.alternativeSuggestion,
        itemName: value.itemName,
        quantity: value.quantity
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    orderId: _OrderId;
    message: string;
    timestamp: _Time;
    senderRole: _SenderRole;
    senderId: Principal;
}): {
    id: MessageId;
    orderId: OrderId;
    message: string;
    timestamp: Time;
    senderRole: SenderRole;
    senderId: Principal;
} {
    return {
        id: value.id,
        orderId: value.orderId,
        message: value.message,
        timestamp: value.timestamp,
        senderRole: from_candid_SenderRole_n23(_uploadFile, _downloadFile, value.senderRole),
        senderId: value.senderId
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    shopId: _ShopId;
    deliveryFee: number;
    createdAt: _Time;
    finalTotal: [] | [number];
    updatedAt: _Time;
    estimatedTotal: number;
    customerId: Principal;
    items: Array<_OrderItem>;
    adminNotes: string;
}): {
    id: OrderId;
    status: OrderStatus;
    shopId: ShopId;
    deliveryFee: number;
    createdAt: Time;
    finalTotal?: number;
    updatedAt: Time;
    estimatedTotal: number;
    customerId: Principal;
    items: Array<OrderItem>;
    adminNotes: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n9(_uploadFile, _downloadFile, value.status),
        shopId: value.shopId,
        deliveryFee: value.deliveryFee,
        createdAt: value.createdAt,
        finalTotal: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.finalTotal)),
        updatedAt: value.updatedAt,
        estimatedTotal: value.estimatedTotal,
        customerId: value.customerId,
        items: from_candid_vec_n12(_uploadFile, _downloadFile, value.items),
        adminNotes: value.adminNotes
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outForDelivery: null;
} | {
    rejected: null;
} | {
    delivered: null;
} | {
    shoppingInProgress: null;
} | {
    received: null;
} | {
    checkingAvailability: null;
}): OrderStatus {
    return "outForDelivery" in value ? OrderStatus.outForDelivery : "rejected" in value ? OrderStatus.rejected : "delivered" in value ? OrderStatus.delivered : "shoppingInProgress" in value ? OrderStatus.shoppingInProgress : "received" in value ? OrderStatus.received : "checkingAvailability" in value ? OrderStatus.checkingAvailability : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    substituted: null;
} | {
    pending: null;
} | {
    confirmed: null;
} | {
    unavailable: null;
}): OrderItemStatus {
    return "substituted" in value ? OrderItemStatus.substituted : "pending" in value ? OrderItemStatus.pending : "confirmed" in value ? OrderItemStatus.confirmed : "unavailable" in value ? OrderItemStatus.unavailable : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customer: null;
}): SenderRole {
    return "admin" in value ? SenderRole.admin : "customer" in value ? SenderRole.customer : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderItem>): Array<OrderItem> {
    return value.map((x)=>from_candid_OrderItem_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n7(_uploadFile, _downloadFile, x));
}
function to_candid_CartItem_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CartItem): _CartItem {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    estimatedPrice: number;
    productId?: ProductId;
    quantity: bigint;
    customItemName?: string;
}): {
    estimatedPrice: number;
    productId: [] | [_ProductId];
    quantity: bigint;
    customItemName: [] | [string];
} {
    return {
        estimatedPrice: value.estimatedPrice,
        productId: value.productId ? candid_some(value.productId) : candid_none(),
        quantity: value.quantity,
        customItemName: value.customItemName ? candid_some(value.customItemName) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    outForDelivery: null;
} | {
    rejected: null;
} | {
    delivered: null;
} | {
    shoppingInProgress: null;
} | {
    received: null;
} | {
    checkingAvailability: null;
} {
    return value == OrderStatus.outForDelivery ? {
        outForDelivery: null
    } : value == OrderStatus.rejected ? {
        rejected: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.shoppingInProgress ? {
        shoppingInProgress: null
    } : value == OrderStatus.received ? {
        received: null
    } : value == OrderStatus.checkingAvailability ? {
        checkingAvailability: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CartItem>): Array<_CartItem> {
    return value.map((x)=>to_candid_CartItem_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
